# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  ms_version: '1.0'
  container_registry: 'dockerhub_demo'

stages:

- stage: BUILD
  displayName: 'Build Microservice'
  jobs:
  - job: Build_Docker_Image
    displayName: Build Docker Image
    steps:
    - task: Docker@2
      displayName: Build Docker Image
      enabled: true
      inputs:
        containerRegistry: 'dockerhub_demo'
        repository: 'demo/hybridapp'
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/webapi.dotnet/Dockerfile'
        arguments: '--no-cache'
        buildContext: '$(Build.SourcesDirectory)/webapi.dotnet'
        tags: '1.0.$(Build.BuildId)'
        addPipelineData: true
