# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

name: $(Build.BuildId).$(Date:yyyyMMdd).$(Rev:r)

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: BUILD
  displayName: 'Build Microservice'
  jobs:
  - job: Build_Docker_Image
    displayName: Build Docker Image
    steps:
    - task: Docker@2
      displayName: Build Docker Image
      enabled: true
      inputs:
        containerRegistry: 'gh-docker-registry-hubrid-demo'
        repository: 'hybrid-demo/hybridappdemo/dotnet-app'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/webapi.dotnet/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/webapi.dotnet'
        tags: '1.0.$(Build.BuildId)'

- stage: Deploy_DEV
  displayName: 'Deploy to DEV'
  jobs:
    - job: Deploy_webapp
      displayName: Deploy webapp
      steps:
      - task: AzureRmWebAppDeployment@4
        displayName: 'Deploy container to Azure AppService'
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'neudesic-free-trial-nasdag-demo-rg'
          appType: 'webAppContainer'
          WebAppName: 'azuredevopsgithub'
          DockerNamespace: 'docker.pkg.github.com'
          DockerRepository: 'hybrid-demo/hybridappdemo/dotnet-app'
          DockerImageTag: '1.0.$(Build.BuildId)'

- stage: Deploy_TEST
  displayName: 'Deploy to TEST'
  jobs:
  - deployment: DeployMSTest
    displayName: Deploy MS in Test
    environment: 
      name: 'test'                
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy container to Azure AppService'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'neudesic-free-trial-nasdag-demo-rg'
              appType: 'webAppContainer'
              WebAppName: 'azuredevopsgithub'
              DockerNamespace: 'docker.pkg.github.com'
              DockerRepository: 'hybrid-demo/hybridappdemo/dotnet-app'
              DockerImageTag: '1.0.$(Build.BuildId)'
